name: uonet_qr
description: UONET+ QR Code converter
version: 1.0.0
repository: https://github.com/wulkanowy/qr/tree/master/dart

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  encrypt: ^4.0.1

dev_dependencies:
  test: ^1.6.0
