version: 2
jobs:
  php:
    working_directory: ~/qr
    docker:
    - image: circleci/php:7
    steps:
    - checkout:
        path: ~/qr
    - run: composer install
    - run: ./vendor/bin/phpunit php/tests
  node:
    working_directory: ~/qr/node
    docker:
    - image: circleci/node:8
    steps:
    - checkout:
        path: ~/qr
    - run: yarn
    - run: yarn test
  jvm:
    working_directory: ~/qr/jvm
    docker:
    - image: circleci/openjdk:8
    steps:
    - checkout:
        path: ~/qr
    - run: ./gradlew check jacocoTestReport
    - store_test_results:
        path: ./build/test-results
  swift:
    working_direcotry: ~/qr/swift
    docker:
    - image: circleci/xcodebuild:13
    steps:
    - checkout:
        path: ~/qr
    - run: xcodebuild -workspace vulcan-qr.xcworkspace -scheme vulcan-qr TEST_AFTER_BUILD=YES


workflows:
  version: 2
  test:
    jobs:
    - php
    - node
    - jvm
    - swift
