version: 2
jobs:
  php:
    working_directory: ~/qr
    docker:
    - image: circleci/php:7
    steps:
    - checkout:
        path: ~/qr
    - run: composer install
    - run: ./vendor/bin/phpunit php/tests
  node:
    working_directory: ~/qr/node
    docker:
    - image: circleci/node:16
    steps:
    - checkout:
        path: ~/qr
    - run: yarn
    - run: yarn test
  jvm:
    working_directory: ~/qr/jvm
    docker:
    - image: circleci/openjdk:11
    steps:
    - checkout:
        path: ~/qr
    - run: ./gradlew check jacocoTestReport
    - store_test_results:
        path: ./build/test-results
  swift:
    working_directory: ~/qr/swift
    build:
        macos:
            xcode: 13.1
    resource_class: large
    steps:
    - checkout:
        path: ~/qr
    - run: xcodebuild -workspace vulcan-qr.xcworkspace -scheme vulcan-qr TEST_AFTER_BUILD=YES
  dart:
    working_directory: ~/qr/dart
    docker:
    - image: google/dart:2.10-dev
    steps:
    - checkout:
        path: ~/qr
    - run: pub get
    - run: pub run test
  dotnet:
    working_directory: ~/qr/dotnet
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout:
          path: ~/qr
      - run: dotnet restore
      - run: dotnet test

workflows:
  version: 2
  test:
    jobs:
    - php
    - node
    - jvm
    - swift
    - dart
    - dotnet
